### ISSUE TITLE
Improve runtime type guarding capabilities of generated Typescript code

### ISSUE THREAD

**Issue by AndrewMD5** [betwixt-labs/bebop#195]
**Is your feature request related to a problem? Please describe.**
When generating Typescript code the Bebop compiler composes the fields of a record into a Typescript interface and creates a constant which defines encode and decode methods that accept that interface. 

So the following schema:
```bebop
union SuperHero {
   1 -> readonly struct GreenLantern {
      float32 powerLevel;
   }
   2 -> readonly struct Batman {
     float32 powerLevel; 
   }
}
```
produces the following code:
```typescript
export declare namespace Bebop.Example {
    interface IGreenLantern {
        readonly powerLevel: number;
    }
    const GreenLantern: {
        discriminator: 1;
        encode(message: IGreenLantern): Uint8Array;
        encodeInto(message: IGreenLantern, view: BebopView): number;
        decode(buffer: Uint8Array): IGreenLantern;
        readFrom(view: BebopView): IGreenLantern;
    };
    interface IBatman {
        readonly powerLevel: number;
    }
    const Batman: {
        discriminator: 2;
        encode(message: IBatman): Uint8Array;
        encodeInto(message: IBatman, view: BebopView): number;
        decode(buffer: Uint8Array): IBatman;
        readFrom(view: BebopView): IBatman;
    };
    type ISuperHero = {
        discriminator: 1;
        value: IGreenLantern;
    } | {
        discriminator: 2;
        value: IBatman;
    };
    const SuperHero: {
        encode(message: ISuperHero): Uint8Array;
        encodeInto(message: ISuperHero, view: BebopView): number;
        decode(buffer: Uint8Array): ISuperHero;
        readFrom(view: BebopView): ISuperHero;
    };
}
```

The promise of Bebop is to be more type-safe than JSON - and at face value this generated code keeps that promise. Now lets define a function that uses this generated code and step through it:
```typescript
function getSuperHero(): Bebop.Example.ISuperHero {
    if (getRandomNumber() > 5) {
        return {
            discriminator: Bebop.Example.Batman.discriminator,
            value: {
                powerLevel: 200
            } as Bebop.Example.IBatman
        }
    }
    return {
        discriminator: Bebop.Example.GreenLantern.discriminator,
        value: {
            powerLevel: 200
        } as Bebop.Example.IGreenLantern
    }
}
```

One of the first issues that presents itself is how a developer must go about constructing and returning a superhero:
```typescript
// creating a superhero is very verbose
return  {
    // while 'discriminator' must be either '1' or '2'
    // there is nothing that prevents a developer from setting the wrong discriminator for a value
    // this can result in subtle and hard to diagnose runtime exceptions
    // especially if a developer fails to use the constant (which they can and will do if given a choice)
    discriminator: Bebop.Example.Batman.discriminator,
   // the type check if done based on the discriminator
   // so even with the 'as` keyword TSC infers the type as whatever matches the `discriminator`
    value: {
        powerLevel: 200
    } as Bebop.Example.IBatman
}
```

Further, because objects are based on interfaces there is no way to implement type guards or differentiate between types:
```typescript
const superHero = getSuperHero();
// not possible 
if (superHero.value instanceof Bebop.Example.IBatman)
// not possible
if (superHero.value instanceof Bebop.Example.IGreenLantern)
// not possible
function isBatman(superHero: Bebop.Example.ISuperHero) {
    return superHero.value instanceof Bebop.Example.Batman;
}
```

Which means the following is the only way to check the type of a value within a union:
```typescript
// this isn't ideal 
if (superHero.discriminator === 1 || superHero.discriminator === Bebop.Example.Batman.discriminator) {
    console.log("I'm Batman")
}
```
And there is no way to check what the type of an object is at all:
```typescript
const batman: Bebop.Example.IBatman = {
    powerLevel: 200
};
// not valid
if (batman instanceof Bebop.Example.IBatman)
```

**Describe the solution you'd like**
The Bebop compiler should produce Typescript code that leverages classes. This would allow not only runtime type checking but also allow unions to be used in a much more ergonomic way, like such:
```typescript
class Superhero {
  discriminator: 1 | 2;
  value:  BaseGreenLantern | BaseBatman;
 
  constructor(value: BaseGreenLantern | BaseBatman) {
    this.value = value;
   if (value instanceof BaseGreenLantern) {
       this.discriminator = 1;
   }
  }
```

That is just one example.

**Comment by AndrewMD5** [comment]
Maybe something like this:
```typescript
export declare namespace Bebop.Example {
    abstract class BaseGreenLatern {
        readonly powerLevel: number;
        constructor(powerLevel: number);
        encode(): Uint8Array;
        static encodeInto(message: BaseGreenLatern, view: BebopView): number;
        abstract decode(buffer: Uint8Array): BaseGreenLatern;
        static decode(buffer: Uint8Array): BaseGreenLatern;
        static readFrom(view: BebopView): BaseGreenLatern;
    }
    class GreenLantern extends BaseGreenLatern {
    }
}
```

Typescript doesn't support static abstracts which is a bit annoying.

**Comment by lynn** [comment]
I talked about this with @bengreenier and we agreed that this change is definitely necessary, but also very breaking. If we implement it, I'd like to put it behind a flag `--tsUseClasses` or something, and then make that the default in bebop v3. :+1:

After this change, every `{x:1, y:2}` needs to be replaced with `new T({x:1, y:2})`. IMO this is good for readability, great for union types, but it definitely breaks all Bebop-using TypeScript code ever, and is btw presumably either-neutral-or-slightly-bad for perf.

Ben and I both don't think we should generate abstract base classes, probably just regular `class GreenLantern` etc, and then a union type is just `export type Superhero = GreenLantern | Batman` and we no longer expose the `discriminator` stuff to the user 🚀

**Comment by AndrewMD5** [comment]
We could have an IGreenLantern and have the class implement that which avoids it being a breaking change. Properties get defined on the interface, and the class is what you type guard against. Polymorphism!

**Comment by Eadword** [comment]
I have been talking a bit with @lynn and I think we should keep what we have right now with a few changes:

1. Rename the `I*` types to be the same as the const (static implementation) since TS allows this overlap and it makes sense in almost all cases.

Example of generated code:
```ts
export interface MyRecord {
  a: string
  b: number
}

export const MyRecord = {
  serialize(data: MyRecord): Uint8Array {...}
  ...
} as const;
```

Example of using:
```ts
import {MyRecord} from './generated'

const a = 'hello'
const b = 5
const r: MyRecord = {a, b}
MyRecord.serialize(r)
```

2. Rename `discriminator` to something that takes less keystrokes. Sounds like `tag` is winning.
3. Generate an enum of the discriminator values for unions. This will make exhaustive checking easier, and more importantly when you want to go over each option you won't have to import each type implementation you are checking for.
4. Use the enum instead of hardcoding them as numbers


Now building on (1) above, this will give the illusion of having classes from a use standpint without having the added weight of classes that thinly wrap the types. IF we use classes, we will probably end up writing something like

```ts
export interface IMyRecord {
  a: string
  b: number
}

class MyRecord implements IMyRecord {
  a: string
  b: number
  
  constructor(raw: IMyRecord) {
    this.a = a
    this.b = b
  }
  
  static deserialize(buffer: Uint8Array): MyRecord {...}
  serialize(): Uint8Array {...}
  ...
}
```

which then means to use you have to write
```ts
const buf = new MyRecord({a, b}).serialize()
```

rather than just
```ts
const buf = MyRecord.serialize({a, b})
```
with my proposal.


Further you add overhead with classes, and unlike in C#, using `instanceof` in JS is not particularly great most of the time. Example:

```ts
abstract class MyUnion { ... }

class MyUnionOptA extends MyUnion {
  tag = 1 as const
  ...
}

class MyUnionOptB extends MyUnion {
  tag: 2 as const
  ...
}
```

You will be unable to do an exhastive check on a param of type `MyUnion` because TS does not recgonize all subclasses as options. Instead you will still have to write
```
function doThing(v: MyUnionOptA | MyUnionOptB) {
  if (v instanceof MyUnionOptA) {...}
  else if (v instanceof MyUnionOptB) {...}
  else { assertUnreachable(v) }
}
```

In my opinion it is much nicer to write
```ts
...
type MyUnion = { tag: MyUnionTag.OptA; value: OptA } | { tag: MyUnionTag.OptB; value: OptB };
...

function doThing(v: MyUnion) {
  switch (v.tag) {
    case MyUnionTag.OptA:
      ...
      break;
    case MyUnionTag.OptB:
      ...
      break;
    default:
      assertUnreachable(v)
  }
}
```
which has the added benefit of most IDEs being able to auto fill in branches for you because it knows all the enum variants.

BTW, `assertUnreachable` is a trival function to define that will force a **compile-time error** if it receives a value that is not `never` which only can happen if you did not exhaustively handle all cases already:
```
function assertUnreachable(v: never): never { throw new Error("This code should never run; check your type definitions!") }
```

**Comment by Eadword** [comment]
Another perk to my suggestions is that they are actually very easy to implement and represent a smaller change to how bebop is used by people.

**Comment by AndrewMD5** [comment]
I disagree. I think the exposure of the discriminator and forcing the user to write their own type guards is a poor design and one that should be addressed. Even in C#, where unions are not actually supported, we don't expose the `discriminator` or force the end-user to worry about it. The promise of Bebop is to bring type-safety and speed in an ergonomic way. Making `discriminator` shorter to type is not the solution.

**Comment by Eadword** [comment]
In typescript, the act of checking the discriminator when the type is defined how we are definining it actually tells the compiler what type it is and correctly enforces all the remaining values. E.g.

```ts
type UnionT = {tag: 1, value: {a: string}} | {tag: 2, value: {b: number}} as const;

const a: UnionT = {tag: 1, value: {a: "hello"}};

// This is a compile time error because if tag == 1, then the key b is not present.
if (a.tag == 1) console.log(`Value: ${a.b}`)

```

**Comment by lynn** [comment]
> Also type narrowing would allow for the IDE to create an exhaustive switch on the users behalf; you wouldn’t need a chain of if statements

You can't use `instanceof` in a `switch` statement in TypeScript, so making this class-y is what would actually force a chain of `if` statements. (You can't write `switch (typeof v) {}`, because the result is `"object"` for all classes.)

TypeScript in VS Code doesn't seem to support "generate switch cases" by default for either approach, but I found [an extension](https://marketplace.visualstudio.com/items?itemName=heroboy.generate-switch-case-for-enum-type) that supports generating cases from `switch (v)` when `v` is a union of constants or an enum.

I am starting to think that neither option is clearly more ergonomic or obvious than the other (they have pros and cons). But as @Eadword  points out, the system we already have works and is type-safe and fast. I'm not sure if the constructor perf hit is too bad, but I think that `instanceof` can involve icky string comparisons and nested [[HasInstance]] function calls etc that I feel a bit weird about, whereas comparing `(value.tag === MyEnum.One)` is definitely super fast at runtime.

So, I am now leaning towards keeping things as they are and making them better in the ways @Eadword listed.

**Comment by e1kin** [comment]
Hello, I’d like to put my two cents:

I really appreciate this library because it doesn't force me to create intermediate objects for serialization.
For example, I can take an instance of my server model class and serialize it easily because my model class implements the same interface as the bebop data object. Or serialize the plain javascript object.

But when you change interfaces to classes with special methods like encode/decode it breaks my case. And I have to create a special intermediate object and call an encoding method on it, or use prototype method call hacks with typescript casting to cheat the typescript type system.

But typescript supports using classes as types. This way we can generate classes with properties only but no logic and put the serialization logic in a special static object. Like this:

```javascript
struct MyObject {
    int32 numericField;
    string stringField;
}

export class MyObject {
  numericField: number;
  stringField: string;
}

export const MyObjectSerializer = {
  encode(message: MyObject): Uint8Array {
  },

  encodeInto(message: MyObject, view: BebopView): number {
  },

  decode(buffer: Uint8Array): MyObject {
  },

  readFrom(view: BebopView): MyObject {
  },
};
```

So, we can pass an instance of the MyObject class or any other object with the same interface to the encode/encodeInto methods. And use runtime checks with instanceof on the result of decode/readFrom calls if we need to.

What do you think about this? What am I missing?
